const fs = require('fs');
const html = fs.readFileSync('tomato (2).html', 'utf8');
const files = [...html.matchAll(/<script src="\.\/([^"]+)"/g)].map(match=>match[1]);
for (const file of files) new Function(fs.readFileSync(file, 'utf8'));
const start = html.lastIndexOf('<script>') + 8, end = html.indexOf('</script>', start);
new Function(html.slice(start, end));
for (const path of files) if (!html.includes('./' + path.replaceAll('\\', '/'))) throw new Error('Arquivo não carregado: ' + path);
const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
if(new Set(ids).size!==ids.length)throw Error('ID HTML duplicado');
for(const [,id] of html.matchAll(/\$\(['"]#([^'"]+)['"]\)/g))if(!ids.includes(id))throw Error('Elemento inexistente: '+id);
console.log('Estrutura e sintaxe validadas.');
